version: '3'
services:
  web:
    image: httpd:latest
    container_name: web-server
    volumes:
      - ./public-html/:/usr/local/apache2/htdocs/
    restart: always
    ports:
      - "80:80"