version: '3'
services:
  dxp1:
    image: liferay/dxp:latest
    environment:
      - LIFERAY_TOMCAT_AJP_PORT=8080
      - LIFERAY_TOMCAT_JVM_ROUTE=node1
      - LIFERAY_WEB_SERVER_DISPLAY_NODE=true

  dxp2:
    image: liferay/dxp:latest
    environment:
      - LIFERAY_TOMCAT_AJP_PORT=8080
      - LIFERAY_TOMCAT_JVM_ROUTE=node2
      - LIFERAY_WEB_SERVER_DISPLAY_NODE=true

  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - dxp1
      - dxp2

